BackendBundle\Entity\Ratings:
    type: entity
    table: ratings
    indexes:
        fk_ratings_users:
            columns:
                - user
        fk_ratings_restaurants:
            columns:
                - restaurant
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        text:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        points:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        restaurant:
            targetEntity: Restaurants
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                restaurant:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
