ratings:
    path: api/ratings/{restaurant}
    defaults: {_controller : ApiBundle:Rating:list,restaurant:null}
rating_new:
    path: api/rating/new
    defaults: {_controller : ApiBundle:Rating:new}
rating_delete:
    path: api/rating/delete/{rating}
    defaults: {_controller : ApiBundle:Rating:delete,rating:null}